/**
 Slugs devem existir na coleção `categories` (ex.: seed-mongodb / painel).
 Grupos do relatório LW (coluna «Grupo») → categoria macro; o texto original continua em `Product.subcategoria` para filtros.

 Serviço Python (`render-catalog-import`): após editar `ENTRIES`, gere `render-catalog-import/grupo_entries.json` com:
 `node scripts/extract-grupo-entries.mjs`
 */
export type MacroCategorySlug =
  | 'cimento-argamassa'
  | 'tijolos-blocos'
  | 'tintas-acessorios'
  | 'ferramentas'
  | 'material-hidraulico'
  | 'material-eletrico';

/** Normaliza rótulo de grupo para chave de pesquisa (trim, espaços, maiúsculas, sem acentos). */
export function normalizeGrupoKey(raw: string | null | undefined): string {
  return String(raw ?? '')
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .replace(/\u00a0/g, ' ')
    .trim()
    .replace(/\s+/g, ' ')
    .toUpperCase();
}

const H = 'material-hidraulico' as const;
const E = 'material-eletrico' as const;
const T = 'tintas-acessorios' as const;
const F = 'ferramentas' as const;
const C = 'cimento-argamassa' as const;
const B = 'tijolos-blocos' as const;

/** Lista (rótulo como no Excel, slug macro). Chaves duplicadas após normalização: última vence. */
const ENTRIES: ReadonlyArray<readonly [string, MacroCategorySlug]> = [
  ['ABRACADEIRAS', H],
  ['ABRACADEIRAS NYLON', H],
  ['ACABAMENTO DOCOL REG.', H],
  ['ACABAMENTO DOCOL VALVULA', H],
  ['ACABAMENTOS', H],
  ['ACABAMENTOS TALITA', H],
  ['ACABAMENTOS VALV. TIGRE', H],
  ['ACESSORIOS DE INOX P/BANHEIRO', H],
  ['ACESSORIOS PARA BANHEIRO METAL', H],
  ['ACESSORIOS VIDRO P/BANHEIRO', H],
  ['ALCA DE APOIO', H],
  ['ALICATE ANEIS', F],
  ['ALICATE BICO CURVO', F],
  ['ALICATE BOMBA', F],
  ['ALICATE DE CORTE', F],
  ['ALICATE FAZENDEIRO', F],
  ['ALICATE MEIA CANA', F],
  ['ALICATE PRESSAO', F],
  ['ALICATE REBITADOR', F],
  ['ALICATE TORQUES', F],
  ['ALICATE TRAVADOR', F],
  ['ALICATE UNIVERSAL', F],
  ['AMIANTO', C],
  ['ANEL DE BORRACHA', H],
  ['ANTENA', E],
  ['ANTI FERRUGEM/LIMPA CONTATO', T],
  ['ANTI IMPACTO', F],
  ['APLICADOR DE SILICONE', T],
  ['ARAMES', F],
  ['ARCO DE PUA', F],
  ['ARCO DE SERRA', F],
  ['AREIA FINA', B],
  ['AREIA GROSSA', B],
  ['AREIA, PEDRA, TELHA E TIJOLO', B],
  ['ARGAMASSA', C],
  ['ARGAMASSA,CAL,CIMENTO E REJUNTE', C],
  ['ARMARIOS E ESPELHOS P/BANHEIRO', H],
  ['ARRUELAS', F],
  ['ARTEFATOS DE CIMENTO', B],
  ['ARTIGOS P/PRESENTE', F],
  ['ARTIGOS PVC', H],
  ['ASPERSOR', H],
  ['ASSENTO SANITARIO', H],
  ['BACIA SANITARIA', H],
  ['BANDEJA P/PINTURA', T],
  ['BARBEADOR', E],
  ['BASE P/PIGMENTO', T],
  ['BATENTE', B],
  ['BATERIA', E],
  ['BICO P/ MANGUEIRA', H],
  ['BLOCO DE ESPUMA', F],
  ['BOMBA SUBMERSA E ACESSORIOS', H],
  ['BOTINAS', F],
  ['BROCA ACO RAPIDO', F],
  ['BROCA CHATA', F],
  ['BROCA DE VIDEA', F],
  ['BROCA FIBROCIMENTO', F],
  ['BROCA MOURAO', F],
  ['BROCA MULTI CONSTRUCAO', F],
  ['BROCA PONTA DE PUA', F],
  ['BROCA PORCELANATO', F],
  ['BROCA SDS', F],
  ['BROCA TRADO', F],
  ['BROCA VIDRO', F],
  ['BUCHA PLASTICA', F],
  ['CABO DE REDE', E],
  ['CABO P/LIMA', F],
  ['CABOS DE MADEIRA', F],
  ['CADEADOS', F],
  ['CAIXA ACOPLADA', H],
  ['CAIXA D AGUA', H],
  ['CAIXA DE DESCARGA', H],
  ['CAIXA DE SOM', E],
  ['CAL', C],
  ['CANETA', F],
  ['CANTONEIRA DE ALUMINIO', B],
  ['CAPACETE DE SEGURANCA', F],
  ['CARRINHO DE MAO', F],
  ['CATRACA P/CERCA', F],
  ['CAVADEIRA ARTICULADA', F],
  ['CAVADEIRA TIPO TRADO', F],
  ['CHAPA MADERITE', B],
  ['CHAPEUS', F],
  ['CHAVE ALLEN', F],
  ['CHAVE BIELA', F],
  ['CHAVE CANHAO', F],
  ['CHAVE COMBINADA', F],
  ['CHAVE DE CANO', F],
  ['CHAVE DE FENDA', F],
  ['CHAVE DE LAVATORIO', F],
  ['CHAVE ELETRICA', F],
  ['CHAVE ESTRELA', F],
  ['CHAVE FIXA', F],
  ['CHAVE INGLESA', F],
  ['CHAVE LIG/DESL', E],
  ['CHAVE P/VIRAR FERRO', F],
  ['CHAVE PHILLIPS', F],
  ['CHAVE TORX', F],
  ['CHURRASQUEIRA DE CHAPA', B],
  ['CHURRASQUEIRAS', B],
  ['CHUVEIRO E COMPLEMENTOS', H],
  ['CHUVEIROS ELETRICOS', H],
  ['CIMENTO', C],
  ['COLA PU', T],
  ['COLA SILICONE', T],
  ['COLAS', T],
  ['COLHER DE PEDREIRO', F],
  ['COLORMAQ', F],
  ['CONDUITES', E],
  ['CONEXAO AQUATERM', H],
  ['CONEXAO PNEUMATICA', F],
  ['CONEXOES - ESGOTO', H],
  ['CONEXOES - POLIETILENO', H],
  ['CONEXOES - ROSQUEAVEL', H],
  ['CONEXOES - SOLDAVEL', H],
  ['CONVERSOR DIGITAL/ANTENAS DIGITAL', E],
  ['CORDAS', F],
  ['CORREIAS', F],
  ['CORRENTES', F],
  ['CORTADOR P/PISO', F],
  ['CUBAS DE INOX', H],
  ['CUBAS DE LOUÇA', H],
  ['CUBAS E LAVATORIOS DE VIDRO', H],
  ['CX CORREIO', B],
  ['CX DE FERRAMENTAS', F],
  ['CX DISTRIBUICAO', E],
  ['CX SIFONADA', H],
  ['Cimento e Argamassa', C],
  ['DESEMP ACO DENTADA', F],
  ['DESEMP ACO LISA', F],
  ['DESEMP MADEIRA', F],
  ['DESEMP P/ GRAFIATO', F],
  ['DESEMP PVC', F],
  ['DESEMP. ESPUMA', F],
  ['DISCO DESBASTE', F],
  ['DISCO DIAMANTADO', F],
  ['DISCO FLAP', F],
  ['DISCO INOX/FERRO/REFRATARIO/MADEIRA /FLAP', F],
  ['DISCO SERRA', F],
  ['DISJUNTORES', E],
  ['DOBRADICAS', F],
  ['DUCHA HIGIENICA', H],
  ['DURIN', H],
  ['ELETROLDO', F],
  ['ELETRONICOS', E],
  ['EMBALAGEM', F],
  ['ENGATE CROMADO', H],
  ['ENGATE P/MANGUEIRA', H],
  ['ENGATE PLASTICO', H],
  ['ENXADA', F],
  ['ENXADAO', F],
  ['ESCADA', F],
  ['ESCOVA DE ACO', F],
  ['ESFREGAO', F],
  ['ESGUICHO', H],
  ['ESPATULA', F],
  ['ESPAÇADOR', F],
  ['ESPELHEIRAS', H],
  ['ESPONJA P/ LIMPEZA', F],
  ['ESQUADRIAS', B],
  ['ESQUADRO', F],
  ['ESTICADOR P/CABO DE ACO', F],
  ['ESTRIBO', B],
  ['EXTENSOR P/ROLO DE PINTURA', T],
  ['FACAO', F],
  ['FECHADURAS 3F', F],
  ['FECHADURAS PADO', F],
  ['FECHADURAS SOPRANO', F],
  ['FECHADURAS, CADEADOS E MACANET', F],
  ['FERRAGENS', F],
  ['FERRAMENTAS ELETRICAS', F],
  ['FERRO DE SOLDA', F],
  ['FERRO P/COSTRUCAO', B],
  ['FIBRA ABRASIVA', F],
  ['FILTRO DE AGUA', H],
  ['FIORI', H],
  ['FIOS E CABOS', E],
  ['FITA ALUMINIZADA', T],
  ['FITA CREPE', T],
  ['FITA DUPLA FACE', F],
  ['FITA ISOLANTE', E],
  ['FITA ZEBRADA', F],
  ['FITAS ANTIDERRAPANTES', F],
  ['FITAS MULTIUSO', F],
  ['FIXADOR P/PISO', B],
  ['FOGAO', E],
  ['FORMAO', F],
  ['FURADEIRA', F],
  ['FURADEIRA SCHULZ', F],
  ['FURADEIRA BLACK DECKER', F],
  ['FURADEIRA BOSCH', F],
  ['FURADEIRA DEWALT', F],
  ['FURADEIRA EINHELL', F],
  ['FUTURA', F],
  ['Ferramentas', F],
  ['GABINETES', H],
  ['GABINETES DE COZINHA', H],
  ['GARRA JACARE', F],
  ['GRAMPO CARPINTEIRO', F],
  ['GRAMPO P/ CAIXARIA', F],
  ['GRELHA', H],
  ['GRELHA INOX/PVC', H],
  ['IMPERMEABILIZANTE', T],
  ['INTERRUPTORES E TOMADAS', E],
  ['INTERRUPTORES E TOMADAS FAME', E],
  ['INTERRUPTORES E TOMADAS ILUMI', E],
  ['INTERRUPTORES E TOMADAS MARGIRIUS', E],
  ['INTERRUPTORES E TOMADAS MECTRONIC', E],
  ['INTERRUPTORES E TOMADAS PERLEX', E],
  ['INTERRUPTORES E TOMADAS PIAL PLUS', E],
  ['INTERRUPTORES E TOMADAS TRAMONTINA', E],
  ['ISQUEIRO', F],
  ['JOELHEIRA DE SEGURANCA', F],
  ['JOGO DE CHAVES', F],
  ['LAMPADAS', E],
  ['LANTERNA', E],
  ['LAVATORIO PVC', H],
  ['LIMA GROSA', F],
  ['LIMPA PISO', T],
  ['LINHA P/PEDREIRO', F],
  ['LIXA AGUA', F],
  ['LIXA DISCO', F],
  ['LIXA FERRO', F],
  ['LIXA MASSA', F],
  ['LIXA SECO', F],
  ['LONA', B],
  ['LOUCAS SANITARIAS', H],
  ['LUKSCOLOR', T],
  ['LUMINARIAS E LUSTRES', E],
  ['LUVA DE RASPA', F],
  ['LUVA LATEX', F],
  ['LUVA NITRILICA', F],
  ['MACHADOS', F],
  ['MADEIRAS', B],
  ['MANGUEIRAS', H],
  ['MANTA ASFALTICA', C],
  ['MARRETAS', F],
  ['MARTELOS', F],
  ['MARTELOS DE BORRACHA', F],
  ['MATERIAIS ELETRICOS', E],
  ['MAXIRUBBER', T],
  ['MESA', F],
  ['METAIS', H],
  ['MOVEIS', F],
  ['Material Elétrico', E],
  ['Material Hidráulico', H],
  ['NIVEL DE ALUMINIO', F],
  ['NIVEL DE MADEIRA', F],
  ['NIVEL PVC', F],
  ['NUMERO RESIDENCIAL', F],
  ['OCULOS DE PROTECAO', F],
  ['ORGANIZADOR PLASTICO', F],
  ['OTTO BAUMGART', B],
  ['PA DE BICO', F],
  ['PA QUADRADA', F],
  ['PALHA DE ACO', F],
  ['PARAFUSO FRANCES', F],
  ['PARAFUSO P/TELHA', F],
  ['PARAFUSO ROSCA SOBERBA', F],
  ['PARAFUSO SEXTAVADO', F],
  ['PARAFUSOS', F],
  ['PARAFUSOS PHILIPS', F],
  ['PARAFUSOS, BUCHAS', F],
  ['PARFUSOS GERAL', F],
  ['PASSARINHEIRA', B],
  ['PASTILHA', B],
  ['PE DE CABRA', F],
  ['PEDRA', B],
  ['PENEIRA', F],
  ['PIAS', H],
  ['PIAS DECORALITA', H],
  ['PIAS VENTURINI', H],
  ['PILHAS', E],
  ['PILHAS/BATERIAS', E],
  ['PINCEIS', T],
  ['PISCINA PLASTICA', B],
  ['PISOS', B],
  ['PISTOLA P/PINTURA', T],
  ['PLAFON LED', E],
  ['PONTA BITS', F],
  ['PORCAS', F],
  ['PORTAS MADEIRA', B],
  ['PORTAS MADEIRA EXPORMAD', B],
  ['PORTAS MADEIRA HIBRA', B],
  ['PORTAS MADEIRA IPUMIRIM', B],
  ['PORTAS MADEIRA RANDA', B],
  ['PORTAS SANFONADAS', B],
  ['PRATELEIRA', F],
  ['PREGOS', F],
  ['PRODUTO ACABADO', B],
  ['PRODUTO CEDRINHO', B],
  ['PRODUTO PINUS', B],
  ['PRODUTOS FERRO FUNDIDO', H],
  ['PRODUTOS P/ CASA', F],
  ['PRODUTOS P/CARRO', F],
  ['PRODUTOS P/PESCA', F],
  ['PRODUTOS PISCINA', B],
  ['PROTETOR AURICULAR', F],
  ['PRUMOS', F],
  ['PULVERIZADOR', F],
  ['PUXADORES', F],
  ['RALO', H],
  ['RASTELO ANCINHO', F],
  ['RATOEIRA', F],
  ['REATORES', E],
  ['REBITES', F],
  ['REFIL GAS', F],
  ['REFIL P/FILTRO', H],
  ['REFLETOR LED', E],
  ['REG.GAVETA', H],
  ['REGUAS', F],
  ['REJUNTE', C],
  ['REPARO', H],
  ['REPARO KELLY', H],
  ['REPARO MARKEMIS', H],
  ['REPARO TALITA', H],
  ['RESISTENCIAS', H],
  ['RESPIRADORES', F],
  ['RODA P/CARRINHO', F],
  ['RODEL P/CORTAR PISO', F],
  ['ROLAMENTO ESFERA', F],
  ['ROLDANA DE FERRO', F],
  ['ROLDANA P/PORTAO', F],
  ['ROLO DE ESPUMA', T],
  ['ROLO DE LA', T],
  ['ROLO DE TEXTURA', T],
  ['SERRA COPO', F],
  ['SERRA MANUAL', F],
  ['SERRA TICO TICO', F],
  ['SERRAS ELETRICAS', F],
  ['SERROTE', F],
  ['SIFAO', H],
  ['SOLVENTES', T],
  ['SOQUETE', E],
  ['SPOT', E],
  ['SUPORTE P/LAVATORIO', H],
  ['SUPORTE P/MANGUEIRA', H],
  ['SUPORTE P/PRATELEIRA', F],
  ['SUPORTE P/TV', E],
  ['TACHO', F],
  ['TALHADEIRA / PONTEIROS', F],
  ['TANQUES DE LOUÇA', H],
  ['TANQUES DECORALITA', H],
  ['TANQUES E TANQUINHO', H],
  ['TARRAXAS', F],
  ['TELAS DE ARAME', B],
  ['TELAS DE NYLON', B],
  ['TELHA LEITOSA', B],
  ['TELHAS DE BARRO', B],
  ['TELHAS DE CONCRETO', B],
  ['TELHAS DE VIDRO', B],
  ['TELHAS FIBROCIMENTO', B],
  ['TELHAS INCOLOR', B],
  ['TESOURA', F],
  ['TESOURA FUNILEIRO', F],
  ['TINTA AUTOMOTIVA', T],
  ['TINTA ESM.LUKSCOLOR', T],
  ['TINTA LATEX', T],
  ['TINTA LATEX HYDRONORTH', T],
  ['TINTA LATEX LUKSCOLOR', T],
  ['TINTA P/PISO', T],
  ['TINTA SPRAY', T],
  ['TINTAS E COMPLEMENTOS', T],
  ['TOMADA EM BARRA', E],
  ['TORNEIRA KELLY', H],
  ['TORNEIRA DOCOL', H],
  ['TORNEIRA DURIN', H],
  ['TORNEIRA ELETRICA', H],
  ['TORNEIRA ESFERA', H],
  ['TORNEIRA LEAO', H],
  ['TORNEIRA LORENZETTI', H],
  ['TORNEIRA SIGMA', H],
  ['TORNEIRAS', H],
  ['TORNEIRAS LGMETAIS', H],
  ['TORNEIRAS PRIME', H],
  ['TORNEIRAS TALITA', H],
  ['TORNEIRAS TIGRE', H],
  ['TORNEIRAS VIQUA', H],
  ['TORNO BANCADA', F],
  ['TRELICA', B],
  ['TRENAS', F],
  ['TRINCOS E FECHOS', F],
  ['TUBO ESGOTO', H],
  ['TUBO POLIETILENO', H],
  ['TUBO ROSQUEAVEL', H],
  ['TUBO SOLDAVEL', H],
  ['TUBOS E CONEXOES - GALVANIZADO', H],
  ['Tijolos e Blocos', B],
  ['Tintas e Acessórios', T],
  ['VALVULA AMERICANA', H],
  ['VALVULA LAV', H],
  ['VALVULA ESF METAL', H],
  ['VALVULA ESF. PVC', H],
  ['VALVULA RETENCAO METAL', H],
  ['VALVULA RETENCAO PVC', H],
  ['VALVULAS ESF', H],
  ['VARAL', F],
  ['VARAO P/CORTINA', F],
  ['VASOS DE BARRO', B],
  ['VASOS PLASTICO', B],
  ['VASSOURA JARDIM', F],
  ['VENTILADORES', E],
  ['VERNIZ', T],
  ['VERRUMAS', F],
  ['VIGA', B],
  ['ZARCAO', T],
];

/** Grupos que usam só a categoria escolhida no painel (fallback). */
const SKIP_NORMALIZED = new Set([
  '',
  'SEM GRUPO',
  'IMPORTADO PDF',
  'TESTE GRUPO',
]);

function buildMap(): Record<string, MacroCategorySlug> {
  const m: Record<string, MacroCategorySlug> = {};
  for (const [label, slug] of ENTRIES) {
    m[normalizeGrupoKey(label)] = slug;
  }
  return m;
}

export const GRUPO_MACRO_SLUG: Readonly<Record<string, MacroCategorySlug>> =
  buildMap();

/** Slug da categoria macro para o grupo; `null` → usar `categoryId` de fallback na importação. */
export function macroCategorySlugForGrupo(
  grupo: string | null | undefined
): MacroCategorySlug | null {
  const k = normalizeGrupoKey(grupo);
  if (SKIP_NORMALIZED.has(k)) return null;
  return GRUPO_MACRO_SLUG[k] ?? null;
}
